#!/usr/bin/env python3
"""KHSEO clean_text — remove hidden AI artifacts from YOUR OWN text before publishing.

What it removes (always):
  * invisible characters used as hidden watermarks or prompt-injection carriers: zero-width
    space/joiners (U+200B–U+200D), word joiner & invisible operators (U+2060–U+2064), BOM
    (U+FEFF), soft hyphen (U+00AD), bidi controls (U+200E/F, U+202A–U+202E, U+2066–U+2069),
    Unicode tag characters (U+E0000–U+E007F), Mongolian vowel separator (U+180E)
  * odd spaces (NBSP, narrow NBSP, thin/hair/figure spaces…) are normalized to a normal space
What it flags (and removes only with --strip-boilerplate):
  * chatbot boilerplate: "As an AI language model", "Certainly! Here's…", "I hope this helps",
    "Let me know if you'd like…", "Generated by AI/ChatGPT"…

What it does NOT do: it doesn't touch copyright notices, attributions or quotes, doesn't remove
watermarks from images, and doesn't claim to make text "undetectable". Cleaning is for your own
content. Honest disclosure rules of your platform still apply.

Usage:
    python clean_text.py in.txt -o out.txt [--strip-boilerplate] [--ascii-punct] [--report]
    cat in.md | python clean_text.py - > out.md
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

INVISIBLE = re.compile("[­᠎​-‏‪-‮⁠-⁤⁦-⁩﻿"
                       "\U000e0000-\U000e007f]")
ODD_SPACES = re.compile("[  -   　]")
ASCII_PUNCT = {"‘": "'", "’": "'", "“": '"', "”": '"', "–": "-", "—": "-",
               "…": "..."}
BOILERPLATE = [
    r"as an ai(?: language)? model[^.!?\n]*[.!?]?",
    r"(?:certainly|sure|absolutely|of course)[!,.]? here(?:'s| is| are)[^\n:]*:?",
    r"here(?:'s| is) (?:the|a|your) (?:revised|rewritten|updated|improved|optimized)[^\n:]*:",
    r"i hope (?:this|that) helps[^.!?\n]*[.!?]?",
    r"let me know if you(?:'d| would) like[^.!?\n]*[.!?]?",
    r"feel free to (?:ask|reach out|let me know)[^.!?\n]*[.!?]?",
    r"(?:this (?:content|article|text) (?:was|is) )?(?:generated|written) (?:by|with|using) (?:ai|chatgpt|gpt-?\d*|claude|gemini)\b[^.\n]*\.?",
    r"\[?(?:ai[- ]generated(?: content)?)\]?",
]
BOILER_RX = [re.compile(p, re.I) for p in BOILERPLATE]


def clean(text: str, strip_boilerplate: bool = False, ascii_punct: bool = False) -> tuple[str, dict]:
    report = {"invisible_removed": len(INVISIBLE.findall(text)),
              "odd_spaces_normalized": len(ODD_SPACES.findall(text)),
              "boilerplate": [], "boilerplate_removed": 0}
    text = INVISIBLE.sub("", text)
    text = ODD_SPACES.sub(" ", text)
    if ascii_punct:
        text = "".join(ASCII_PUNCT.get(c, c) for c in text)
    for i, line in enumerate(text.splitlines(), 1):
        spans = sorted({m.span() for rx in BOILER_RX for m in rx.finditer(line)}, key=lambda sp: (sp[0], -sp[1]))
        end = -1
        for a0, a1 in spans:  # report overlapping matches once (keep the widest)
            if a0 >= end:
                report["boilerplate"].append({"line": i, "text": line[a0:a1].strip()[:100]})
                end = a1
    if strip_boilerplate:
        for rx in BOILER_RX:
            text, n = rx.subn("", text)
            report["boilerplate_removed"] += n
        text = re.sub(r"[ \t]{2,}", " ", text)
        text = re.sub(r"(?m)[ \t]+$", "", text)  # trailing spaces left where phrases were removed
        text = re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"
    return text, report


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Remove hidden AI artifacts from your own text")
    ap.add_argument("input", help="file path or - for stdin")
    ap.add_argument("-o", "--out", help="output file (default stdout)")
    ap.add_argument("--strip-boilerplate", action="store_true", help="also delete chatbot boilerplate phrases")
    ap.add_argument("--ascii-punct", action="store_true", help="curly quotes/dashes/ellipsis to ASCII")
    ap.add_argument("--report", action="store_true", help="print a JSON report to stderr")
    a = ap.parse_args(argv)
    try:
        raw = sys.stdin.read() if a.input == "-" else Path(a.input).read_text(encoding="utf-8")
    except OSError as e:
        print(f"clean_text: {e}", file=sys.stderr)
        return 2
    out, rep = clean(raw, a.strip_boilerplate, a.ascii_punct)
    if a.out:
        Path(a.out).write_text(out, encoding="utf-8")
    else:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stdout.write(out)
    if a.report or a.out:
        print(json.dumps(rep, indent=2, ensure_ascii=False), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
